services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://appuser:secret@db:5432/appdb
      PYTHONUNBUFFERED: 1
      MQ_HOST: mq
      MQ_PORT: 5672
      MQ_USER: guest
      MQ_PASSWORD: guest
    depends_on:
      - db
      - mq
  flask-app:
    build: ./flask-app
    ports:
      - "8001:8001"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
      MQ_HOST: mq
      MQ_PORT: 5672
      MQ_USER: guest
      MQ_PASSWORD: guest
  order-processor:
    build: ./jobs/order_processor
    environment:
      DATABASE_URL: postgresql://appuser:secret@db:5432/appdb
      MQ_HOST: mq
      MQ_PORT: 5672
      MQ_USER: guest
      MQ_PASSWORD: guest
    depends_on:
      - db
      - mq
volumes:
  db_data:
